<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>

<img class="photo image"
    <?= /* @escapeNotVerified */ $block->getCustomAttributes() ?>
    data-mage-init='{"mouseoverImage":{}}'
    src="<?= /* @escapeNotVerified */ $block->getImageUrl() ?>"
    data-alt-src="<?= $block->getData(\Space48\MouseOverImage\Plugin\Catalog\Product\ImageFactoryPlugin::IMAGE_BLOCK_URL_KEY) ?>"
    width="<?= /* @escapeNotVerified */ $block->getWidth() ?>"
    height="<?= /* @escapeNotVerified */ $block->getHeight() ?>"
    alt="<?= /* @escapeNotVerified */ $block->stripTags($block->getLabel(), null, true) ?>" />
